kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gateway-service-v1
  namespace: smi
  labels:
    app: gateway-service-v1
    app.kubernetes.io/component: gateway-service-v1
    app.kubernetes.io/instance: gateway-service-v1
spec:
  host: api.apps.los.mylabzolution.com
  path: /gateway-service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: gateway-service-v1
    weight: 100
  port:
    targetPort: 80-tcp
  wildcardPolicy: None
