kind: Service
apiVersion: v1
metadata:
  name: gateway-service-v1
  namespace: smi
  labels:
    app: gateway-service-v1
    app.kubernetes.io/component: gateway-service-v1
    app.kubernetes.io/instance: gateway-service-v1
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deploymentconfig: gateway-service-v1
