basePath: /gateway-service
server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        provider:
          custom:
            token-uri: lb://AUTHORIZATION-SERVICE/auth/validate
  application:
    name: ejourney-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
      routes:
        - id: PRODUCTION-SERVICE
          uri: http://172.17.0.1:8081
          predicates:
            - Path=${basePath}/**
          filters:
            - RewritePath=${basePath}/(?<segment>.*), /$\{segment}
        - id: DEVELOPMENT-SERVICE
          uri: https://osprey-big-wildcat.ngrok-free.app
          predicates:
            - Path=${basePath}/dev/**
          filters:
            - RewritePath=${basePath}/dev/(?<segment>.*), /$\{segment}
authentication:
  enabled: false
redis:
  host: 34.101.154.7
  port: 63796
  database: 0